import React from 'react';
import 'katex/dist/katex.min.css';
import { BlockMath } from 'react-katex';

const Chicklet = function ({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="p-4 bg-white rounded-lg border border-gray-100">
      <h4 className="font-medium text-slate-600 mb-2">{title}</h4>
      <p className="text-gray-600">{children}</p>
    </div>
  );
};

const KeyValuationConcepts = () => {
  return (
    <section className="mt-8">
      <article className="p-2 md:p-8 md:bg-gray-50 md:rounded-xl md:border md:border-gray-200">
        <div>
          <h3 className="text-xl font-semibold text-gray-800 mb-4">
            Key Valuation Concepts Used
          </h3>
          <div className="space-y-4 bg-gray-50 md:bg-white p-2 md:p-6 rounded-lg border border-gray-100">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              <Chicklet title="Monte Carlo Simulation">
                Thousands of iterations with varying inputs to model uncertainty
                in valuation parameters
              </Chicklet>
              <Chicklet title="Earnings Per Share">
                Portion of a company&apos;s profit allocated to each outstanding
                share of common stock
              </Chicklet>
              <Chicklet title="Free Cash Flow">
                Cash generated by a company after accounting for capital
                expenditures
              </Chicklet>
              <Chicklet title="Growth Rate Distribution">
                Log-normal distribution skewed towards moderate growth
              </Chicklet>
              <Chicklet title="Reverse Discounted Cash Flow">
                Calculate the{' '}
                <a
                  href="https://github.com/jawadshuaib/stock-valuation/blob/main/documentation/ReverseDCFExplanation.md"
                  target="_blank"
                  rel="noreferrer"
                  className="underline hover:no-underline"
                >
                  implied growth rate
                </a>{' '}
                based on market expectations.
              </Chicklet>
              <Chicklet title="Growth Decay">
                Natural{' '}
                <a
                  href="https://github.com/jawadshuaib/stock-valuation/blob/main/documentation/GrowthRateDecayExplanation.md"
                  target="_blank"
                  rel="noreferrer"
                  className="underline hover:no-underline"
                >
                  declination of growth rates
                </a>{' '}
                over time to more sustainable levels
              </Chicklet>
            </div>
          </div>
        </div>

        <div className="mt-4">
          <h3 className="text-xl font-semibold text-gray-800 mb-4">
            Mathematical Foundation
          </h3>
          <div className="space-y-4 bg-white p-6 rounded-lg border border-gray-100">
            <div className="space-y-2">
              <div className="font-medium text-gray-700">Core Formulas:</div>
              <div className="md:pl-4 space-y-2 font-mono text-xs md:text-sm">
                <BlockMath math="Present\ Value = \dfrac{Future\ Value}{(1 + r)^n}" />
                <BlockMath math="Growth\ Rate \sim LogNormal(\mu, \sigma)" />
                <BlockMath math="Terminal\ Value = Future\ Value \cdot \dfrac{1 + g}{r - g}" />
                <BlockMath math="Implied\ Growth\ Rate = tGR + (iGR - tGR) \cdot \exp(-dF \cdot (n - 1))" />
              </div>
            </div>

            <div className="border-t border-gray-100 pt-4">
              <div className="font-medium text-gray-700 mb-2">Where:</div>
              <div className="grid grid-cols-2 md:grid-cols-3 gap-2 text-sm text-gray-600">
                <div>r = discount rate</div>
                <div>g = growth rate</div>
                <div>n = number of years</div>
                <div>μ = mean of log growth</div>
                <div>σ = standard deviation</div>
                <div>tGR = terminal Growth Rate</div>
                <div>iGR = initial Growth Rate</div>
                <div>dF = decay Factor</div>
              </div>
            </div>
          </div>
        </div>
      </article>
    </section>
  );
};

export default KeyValuationConcepts;
