import React from 'react';
import 'katex/dist/katex.min.css';
import { BlockMath } from 'react-katex';

const Chicklet = function ({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="p-4 bg-white rounded-lg border border-gray-100">
      <h4 className="font-medium text-slate-600 mb-2">{title}</h4>
      <p className="text-gray-600">{children}</p>
    </div>
  );
};

const KeyValuationConcepts = () => {
  return (
    <section className="mt-8">
      <article className="p-8 bg-gray-50 rounded-xl border border-gray-200">
        <div>
          <h3 className="text-xl font-semibold text-gray-800 mb-4">
            Key Valuation Concepts
          </h3>
          <div className="space-y-4 bg-white p-6 rounded-lg border border-gray-100">
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
              <Chicklet title="Monte Carlo Simulation">
                Statistical method that runs thousands of iterations with
                varying inputs to model uncertainty in valuation parameters
              </Chicklet>
              <Chicklet title="Earnings Per Share">
                Portion of a company&apos;s profit allocated to each outstanding
                share of common stock
              </Chicklet>
              <Chicklet title="Free Cash Flow">
                Cash generated by a company after accounting for capital
                expenditures
              </Chicklet>
              <Chicklet title="Growth Rate Distribution">
                Log-normal distribution to skew towards moderate growth with
                potential for outliers
              </Chicklet>
              <Chicklet title="Terminal Value">
                Company&apos;s estimated value into perpetuity
              </Chicklet>
              <Chicklet title="Margin of Safety">
                Buffer against estimation errors and market volatility
              </Chicklet>
            </div>
          </div>
        </div>

        <div className="mt-4">
          <h3 className="text-xl font-semibold text-gray-800 mb-4">
            Mathematical Foundation
          </h3>
          <div className="space-y-4 bg-white p-6 rounded-lg border border-gray-100">
            <div className="space-y-2">
              <div className="font-medium text-gray-700">Core Formulas:</div>
              <div className="pl-4 space-y-2 font-mono text-sm">
                <BlockMath math="Present\ Value = \dfrac{Future\ Value}{(1 + r)^n}" />
                <BlockMath math="Growth\ Rate \sim LogNormal(\mu, \sigma)" />
                <BlockMath math="Terminal\ Value = Future\ Value \cdot \dfrac{1 + g}{r - g}" />
              </div>
            </div>

            <div className="border-t border-gray-100 pt-4">
              <div className="font-medium text-gray-700 mb-2">Where:</div>
              <div className="grid grid-cols-2 md:grid-cols-3 gap-2 text-sm text-gray-600">
                <div>r = discount rate</div>
                <div>g = growth rate</div>
                <div>n = number of years</div>
                <div>μ = mean of log growth</div>
                <div>σ = standard deviation</div>
              </div>
            </div>
          </div>
        </div>
      </article>
    </section>
  );
};

export default KeyValuationConcepts;
