import React, { useState } from 'react';

interface SectionProps {
  title: string;
  content: React.ReactNode;
  id: string;
}

const PrivacyPolicy = () => {
  const [openSections, setOpenSections] = useState<{ [key: string]: boolean }>(
    {},
  );

  const toggleSection = (section: string) => {
    setOpenSections((prev) => ({
      ...prev,
      [section]: !prev[section],
    }));
  };

  const Section: React.FC<SectionProps> = ({ title, content, id }) => (
    <div className="border-b border-gray-300 pb-4 mb-4">
      <button
        onClick={() => toggleSection(id)}
        className="w-full text-left font-semibold text-lg text-gray-800 hover:text-blue-500 focus:outline-none"
      >
        {title}
        <span className="float-right">{openSections[id] ? '-' : '+'}</span>
      </button>
      {openSections[id] && <div className="mt-2 text-gray-700">{content}</div>}
    </div>
  );

  return (
    <div className="max-w-4xl mx-auto p-6 bg-white rounded-lg shadow-md">
      <h1 className="text-2xl font-bold text-center text-gray-900 mb-6">
        Privacy Policy for API Usage
      </h1>
      <Section
        id="introduction"
        title="Introduction"
        content={
          <p>
            Stock Valuation Calculator (&quot;we&quot;, &quot;us&quot;,
            &quot;our&quot;) is committed to protecting the privacy of our
            users. This Privacy Policy describes how we collect, use, and
            protect your information when you use our API for intrinsic value
            calculations based on Free Cash Flow (FCF) and Earnings Per Share
            (EPS). By using our API, you agree to the terms outlined in this
            policy.
          </p>
        }
      />
      <Section
        id="information-we-collect"
        title="Information We Collect"
        content={
          <>
            <ul className="list-disc ml-5 space-y-2">
              <li>
                <strong>API Usage Data:</strong>We do not collect information
                such as request data and timestamps.
              </li>
              <li>
                <strong>Personal Information:</strong>We do not collect contact
                details and account-related data for API key registration.
              </li>
              <li>
                <strong>Derived and Aggregated Data:</strong>We do not collect
                results generated by the API.
              </li>
            </ul>
          </>
        }
      />
      <Section
        id="how-we-use"
        title="How We Use Your Information"
        content={
          <ul className="list-disc ml-5 space-y-2">
            <li>Service delivery for processing requests and API results.</li>
            <li>Account management and communication.</li>
            <li>Analytics and improvement based on anonymized usage data.</li>
            <li>Compliance with legal obligations and fraud prevention.</li>
          </ul>
        }
      />
      <Section
        id="sharing-and-disclosure"
        title="Information Sharing and Disclosure"
        content={
          <ul className="list-disc ml-5 space-y-2">
            <li>
              Sharing with trusted service providers for operations like hosting
              and analytics.
            </li>
            <li>Disclosure to comply with legal requirements.</li>
          </ul>
        }
      />
      <Section
        id="data-retention-security"
        title="Data Retention and Security"
        content={
          <>
            <p>
              <strong>Retention:</strong> Data is not retained for any purpose.
            </p>
            <p>
              <strong>Security:</strong> Measures include encryption, and secure
              API access.
            </p>
          </>
        }
      />
      <Section
        id="third-party-links"
        title="Third-Party Links and Data Sources"
        content={
          <p>
            Our API integrates with OpenAI. We are not responsible for
            third-party data accuracy or privacy practices.
          </p>
        }
      />
      <Section
        id="policy-changes"
        title="Changes to This Privacy Policy"
        content={
          <p>
            Updates to this policy will be posted here. Significant changes will
            be communicated via email or other means.
          </p>
        }
      />
      <Section
        id="contact-us"
        title="Contact Us"
        content={
          <p>
            If you have any questions, please contact us at:
            <br />
            <strong>Email:</strong> jawad.php@gmail.com
          </p>
        }
      />
    </div>
  );
};

export default PrivacyPolicy;
