export const EMOJIS = {
  tick: '✅',
  warning: '🟡',
  star: '🌟',
  smiling: '😊',
  unsure: '😐',
  rocket: '🚀',
  thumbsdown: '👎',
  // growth: '🌱',
  // loot: '💰',
  // market: '📊',
  // stocks: '📈',
  // decay: '🍂',
  // dollars: '💵',
};
